/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowcaseWritingSessionRouteImport } from './routes/showcase.writing-session'
import { Route as ShowcaseStudioDashboardRouteImport } from './routes/showcase.studio-dashboard'
import { Route as ShowcaseStoryWorldRouteImport } from './routes/showcase.story-world'
import { Route as ShowcaseStoryWizardRouteImport } from './routes/showcase.story-wizard'
import { Route as ShowcaseStoryHeroRouteImport } from './routes/showcase.story-hero'
import { Route as ShowcaseStoryDetailRouteImport } from './routes/showcase.story-detail'
import { Route as ShowcaseStoryCardRouteImport } from './routes/showcase.story-card'
import { Route as ShowcaseSectionRouteImport } from './routes/showcase.section'
import { Route as ShowcaseReadingRouteImport } from './routes/showcase.reading'
import { Route as ShowcaseFranchiseCardRouteImport } from './routes/showcase.franchise-card'
import { Route as ShowcaseCollectionCardRouteImport } from './routes/showcase.collection-card'
import { Route as ShowcaseCarouselRouteImport } from './routes/showcase.carousel'
import { Route as ShowcaseAuthorCardRouteImport } from './routes/showcase.author-card'
import { Route as ReadStoryIdRouteImport } from './routes/read.$storyId'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseWritingSessionRoute = ShowcaseWritingSessionRouteImport.update({
  id: '/showcase/writing-session',
  path: '/showcase/writing-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseStudioDashboardRoute = ShowcaseStudioDashboardRouteImport.update({
  id: '/showcase/studio-dashboard',
  path: '/showcase/studio-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseStoryWorldRoute = ShowcaseStoryWorldRouteImport.update({
  id: '/showcase/story-world',
  path: '/showcase/story-world',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseStoryWizardRoute = ShowcaseStoryWizardRouteImport.update({
  id: '/showcase/story-wizard',
  path: '/showcase/story-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseStoryHeroRoute = ShowcaseStoryHeroRouteImport.update({
  id: '/showcase/story-hero',
  path: '/showcase/story-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseStoryDetailRoute = ShowcaseStoryDetailRouteImport.update({
  id: '/showcase/story-detail',
  path: '/showcase/story-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseStoryCardRoute = ShowcaseStoryCardRouteImport.update({
  id: '/showcase/story-card',
  path: '/showcase/story-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseSectionRoute = ShowcaseSectionRouteImport.update({
  id: '/showcase/section',
  path: '/showcase/section',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseReadingRoute = ShowcaseReadingRouteImport.update({
  id: '/showcase/reading',
  path: '/showcase/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseFranchiseCardRoute = ShowcaseFranchiseCardRouteImport.update({
  id: '/showcase/franchise-card',
  path: '/showcase/franchise-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseCollectionCardRoute = ShowcaseCollectionCardRouteImport.update({
  id: '/showcase/collection-card',
  path: '/showcase/collection-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseCarouselRoute = ShowcaseCarouselRouteImport.update({
  id: '/showcase/carousel',
  path: '/showcase/carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseAuthorCardRoute = ShowcaseAuthorCardRouteImport.update({
  id: '/showcase/author-card',
  path: '/showcase/author-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadStoryIdRoute = ReadStoryIdRouteImport.update({
  id: '/read/$storyId',
  path: '/read/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/library': typeof LibraryRoute
  '/studio': typeof StudioRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/showcase/author-card': typeof ShowcaseAuthorCardRoute
  '/showcase/carousel': typeof ShowcaseCarouselRoute
  '/showcase/collection-card': typeof ShowcaseCollectionCardRoute
  '/showcase/franchise-card': typeof ShowcaseFranchiseCardRoute
  '/showcase/reading': typeof ShowcaseReadingRoute
  '/showcase/section': typeof ShowcaseSectionRoute
  '/showcase/story-card': typeof ShowcaseStoryCardRoute
  '/showcase/story-detail': typeof ShowcaseStoryDetailRoute
  '/showcase/story-hero': typeof ShowcaseStoryHeroRoute
  '/showcase/story-wizard': typeof ShowcaseStoryWizardRoute
  '/showcase/story-world': typeof ShowcaseStoryWorldRoute
  '/showcase/studio-dashboard': typeof ShowcaseStudioDashboardRoute
  '/showcase/writing-session': typeof ShowcaseWritingSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/library': typeof LibraryRoute
  '/studio': typeof StudioRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/showcase/author-card': typeof ShowcaseAuthorCardRoute
  '/showcase/carousel': typeof ShowcaseCarouselRoute
  '/showcase/collection-card': typeof ShowcaseCollectionCardRoute
  '/showcase/franchise-card': typeof ShowcaseFranchiseCardRoute
  '/showcase/reading': typeof ShowcaseReadingRoute
  '/showcase/section': typeof ShowcaseSectionRoute
  '/showcase/story-card': typeof ShowcaseStoryCardRoute
  '/showcase/story-detail': typeof ShowcaseStoryDetailRoute
  '/showcase/story-hero': typeof ShowcaseStoryHeroRoute
  '/showcase/story-wizard': typeof ShowcaseStoryWizardRoute
  '/showcase/story-world': typeof ShowcaseStoryWorldRoute
  '/showcase/studio-dashboard': typeof ShowcaseStudioDashboardRoute
  '/showcase/writing-session': typeof ShowcaseWritingSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/library': typeof LibraryRoute
  '/studio': typeof StudioRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/showcase/author-card': typeof ShowcaseAuthorCardRoute
  '/showcase/carousel': typeof ShowcaseCarouselRoute
  '/showcase/collection-card': typeof ShowcaseCollectionCardRoute
  '/showcase/franchise-card': typeof ShowcaseFranchiseCardRoute
  '/showcase/reading': typeof ShowcaseReadingRoute
  '/showcase/section': typeof ShowcaseSectionRoute
  '/showcase/story-card': typeof ShowcaseStoryCardRoute
  '/showcase/story-detail': typeof ShowcaseStoryDetailRoute
  '/showcase/story-hero': typeof ShowcaseStoryHeroRoute
  '/showcase/story-wizard': typeof ShowcaseStoryWizardRoute
  '/showcase/story-world': typeof ShowcaseStoryWorldRoute
  '/showcase/studio-dashboard': typeof ShowcaseStudioDashboardRoute
  '/showcase/writing-session': typeof ShowcaseWritingSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/library'
    | '/studio'
    | '/read/$storyId'
    | '/showcase/author-card'
    | '/showcase/carousel'
    | '/showcase/collection-card'
    | '/showcase/franchise-card'
    | '/showcase/reading'
    | '/showcase/section'
    | '/showcase/story-card'
    | '/showcase/story-detail'
    | '/showcase/story-hero'
    | '/showcase/story-wizard'
    | '/showcase/story-world'
    | '/showcase/studio-dashboard'
    | '/showcase/writing-session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/library'
    | '/studio'
    | '/read/$storyId'
    | '/showcase/author-card'
    | '/showcase/carousel'
    | '/showcase/collection-card'
    | '/showcase/franchise-card'
    | '/showcase/reading'
    | '/showcase/section'
    | '/showcase/story-card'
    | '/showcase/story-detail'
    | '/showcase/story-hero'
    | '/showcase/story-wizard'
    | '/showcase/story-world'
    | '/showcase/studio-dashboard'
    | '/showcase/writing-session'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/library'
    | '/studio'
    | '/read/$storyId'
    | '/showcase/author-card'
    | '/showcase/carousel'
    | '/showcase/collection-card'
    | '/showcase/franchise-card'
    | '/showcase/reading'
    | '/showcase/section'
    | '/showcase/story-card'
    | '/showcase/story-detail'
    | '/showcase/story-hero'
    | '/showcase/story-wizard'
    | '/showcase/story-world'
    | '/showcase/studio-dashboard'
    | '/showcase/writing-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  LibraryRoute: typeof LibraryRoute
  StudioRoute: typeof StudioRoute
  ReadStoryIdRoute: typeof ReadStoryIdRoute
  ShowcaseAuthorCardRoute: typeof ShowcaseAuthorCardRoute
  ShowcaseCarouselRoute: typeof ShowcaseCarouselRoute
  ShowcaseCollectionCardRoute: typeof ShowcaseCollectionCardRoute
  ShowcaseFranchiseCardRoute: typeof ShowcaseFranchiseCardRoute
  ShowcaseReadingRoute: typeof ShowcaseReadingRoute
  ShowcaseSectionRoute: typeof ShowcaseSectionRoute
  ShowcaseStoryCardRoute: typeof ShowcaseStoryCardRoute
  ShowcaseStoryDetailRoute: typeof ShowcaseStoryDetailRoute
  ShowcaseStoryHeroRoute: typeof ShowcaseStoryHeroRoute
  ShowcaseStoryWizardRoute: typeof ShowcaseStoryWizardRoute
  ShowcaseStoryWorldRoute: typeof ShowcaseStoryWorldRoute
  ShowcaseStudioDashboardRoute: typeof ShowcaseStudioDashboardRoute
  ShowcaseWritingSessionRoute: typeof ShowcaseWritingSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/writing-session': {
      id: '/showcase/writing-session'
      path: '/showcase/writing-session'
      fullPath: '/showcase/writing-session'
      preLoaderRoute: typeof ShowcaseWritingSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/studio-dashboard': {
      id: '/showcase/studio-dashboard'
      path: '/showcase/studio-dashboard'
      fullPath: '/showcase/studio-dashboard'
      preLoaderRoute: typeof ShowcaseStudioDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/story-world': {
      id: '/showcase/story-world'
      path: '/showcase/story-world'
      fullPath: '/showcase/story-world'
      preLoaderRoute: typeof ShowcaseStoryWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/story-wizard': {
      id: '/showcase/story-wizard'
      path: '/showcase/story-wizard'
      fullPath: '/showcase/story-wizard'
      preLoaderRoute: typeof ShowcaseStoryWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/story-hero': {
      id: '/showcase/story-hero'
      path: '/showcase/story-hero'
      fullPath: '/showcase/story-hero'
      preLoaderRoute: typeof ShowcaseStoryHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/story-detail': {
      id: '/showcase/story-detail'
      path: '/showcase/story-detail'
      fullPath: '/showcase/story-detail'
      preLoaderRoute: typeof ShowcaseStoryDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/story-card': {
      id: '/showcase/story-card'
      path: '/showcase/story-card'
      fullPath: '/showcase/story-card'
      preLoaderRoute: typeof ShowcaseStoryCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/section': {
      id: '/showcase/section'
      path: '/showcase/section'
      fullPath: '/showcase/section'
      preLoaderRoute: typeof ShowcaseSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/reading': {
      id: '/showcase/reading'
      path: '/showcase/reading'
      fullPath: '/showcase/reading'
      preLoaderRoute: typeof ShowcaseReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/franchise-card': {
      id: '/showcase/franchise-card'
      path: '/showcase/franchise-card'
      fullPath: '/showcase/franchise-card'
      preLoaderRoute: typeof ShowcaseFranchiseCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/collection-card': {
      id: '/showcase/collection-card'
      path: '/showcase/collection-card'
      fullPath: '/showcase/collection-card'
      preLoaderRoute: typeof ShowcaseCollectionCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/carousel': {
      id: '/showcase/carousel'
      path: '/showcase/carousel'
      fullPath: '/showcase/carousel'
      preLoaderRoute: typeof ShowcaseCarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/author-card': {
      id: '/showcase/author-card'
      path: '/showcase/author-card'
      fullPath: '/showcase/author-card'
      preLoaderRoute: typeof ShowcaseAuthorCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$storyId': {
      id: '/read/$storyId'
      path: '/read/$storyId'
      fullPath: '/read/$storyId'
      preLoaderRoute: typeof ReadStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  LibraryRoute: LibraryRoute,
  StudioRoute: StudioRoute,
  ReadStoryIdRoute: ReadStoryIdRoute,
  ShowcaseAuthorCardRoute: ShowcaseAuthorCardRoute,
  ShowcaseCarouselRoute: ShowcaseCarouselRoute,
  ShowcaseCollectionCardRoute: ShowcaseCollectionCardRoute,
  ShowcaseFranchiseCardRoute: ShowcaseFranchiseCardRoute,
  ShowcaseReadingRoute: ShowcaseReadingRoute,
  ShowcaseSectionRoute: ShowcaseSectionRoute,
  ShowcaseStoryCardRoute: ShowcaseStoryCardRoute,
  ShowcaseStoryDetailRoute: ShowcaseStoryDetailRoute,
  ShowcaseStoryHeroRoute: ShowcaseStoryHeroRoute,
  ShowcaseStoryWizardRoute: ShowcaseStoryWizardRoute,
  ShowcaseStoryWorldRoute: ShowcaseStoryWorldRoute,
  ShowcaseStudioDashboardRoute: ShowcaseStudioDashboardRoute,
  ShowcaseWritingSessionRoute: ShowcaseWritingSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
